name: Wasm publish to NPM

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to run publish from'
        required: true
      tag:
        description: 'Tag to publish to NPM under'
        required: false

jobs:
  publish-rust:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.branch }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'

      - name: Install Yarn
        run: npm i -g yarn
        working-directory: bindings/wasm

      - name: Install JS dependencies
        run: yarn
        working-directory: bindings/wasm

      - name: Install JS dependencies
        run: yarn build
        working-directory: bindings/wasm

      - name: Publish WASM bindings to NPM
        shell: sh
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        # will publish 'latest' tag if no tag is passed
        run: npm publish $(if [ ${{ inputs.tag }} != '' ]; then echo --tag ${{ inputs.tag }}; fi) --access public
        working-directory: bindings/wasm
